--MemberDao.getMember(int page)//size받으면 뿌려주는 수가 많아짐
SELECT * FROM MEMBERS;
SELECT * FROM (SELECT ROWNUM NUM, A.* FROM (SELECT * FROM MEMBERS ORDER BY REGDATE DESC)A)
WHERE NUM BETWEEN 11 AND 20;

